INSERT INTO users (id, email, name, preferred_language, protein_aim,
                   fat_aim, carbohydrates_aim, calories_aim,
                   email_confirmed, password, roles)
VALUES (1,
        'yva@test.com',
        'name',
        'UA',
        120,
        50,
        200,
        1000,
        TRUE,
        'pass',
        'USER'),
       (2,
        '2@test.com',
        'name 2',
        'UA',
        130,
        60,
        400,
        1500,
        TRUE,
        'pass2',
        'USER');
