/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Public;
import org.mvasylchuk.pfcc.jooq.tables.records.DishIngredientsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DishIngredients extends TableImpl<DishIngredientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dish_ingredients</code>
     */
    public static final DishIngredients DISH_INGREDIENTS = new DishIngredients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DishIngredientsRecord> getRecordType() {
        return DishIngredientsRecord.class;
    }

    /**
     * The column <code>public.dish_ingredients.dish_id</code>.
     */
    public final TableField<DishIngredientsRecord, Long> DISH_ID = createField(DSL.name("dish_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.dish_ingredients.ingredient_id</code>.
     */
    public final TableField<DishIngredientsRecord, Long> INGREDIENT_ID = createField(DSL.name("ingredient_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.dish_ingredients.ingredient_weight</code>.
     */
    public final TableField<DishIngredientsRecord, BigDecimal> INGREDIENT_WEIGHT = createField(DSL.name("ingredient_weight"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.dish_ingredients.ingredient_index</code>.
     */
    public final TableField<DishIngredientsRecord, Long> INGREDIENT_INDEX = createField(DSL.name("ingredient_index"), SQLDataType.BIGINT.nullable(false), this, "");

    private DishIngredients(Name alias, Table<DishIngredientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DishIngredients(Name alias, Table<DishIngredientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.dish_ingredients</code> table reference
     */
    public DishIngredients(String alias) {
        this(DSL.name(alias), DISH_INGREDIENTS);
    }

    /**
     * Create an aliased <code>public.dish_ingredients</code> table reference
     */
    public DishIngredients(Name alias) {
        this(alias, DISH_INGREDIENTS);
    }

    /**
     * Create a <code>public.dish_ingredients</code> table reference
     */
    public DishIngredients() {
        this(DSL.name("dish_ingredients"), null);
    }

    public <O extends Record> DishIngredients(Table<O> child, ForeignKey<O, DishIngredientsRecord> key) {
        super(child, key, DISH_INGREDIENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DishIngredientsRecord> getPrimaryKey() {
        return Keys.DISH_INGREDIENTS_PKEY;
    }

    @Override
    public List<ForeignKey<DishIngredientsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DISH_INGREDIENTS__DISH_INGREDIENTS_DISH_ID_FKEY, Keys.DISH_INGREDIENTS__DISH_INGREDIENTS_INGREDIENT_ID_FKEY);
    }

    private transient Dish _dish;
    private transient Food _food;

    /**
     * Get the implicit join path to the <code>public.dish</code> table.
     */
    public Dish dish() {
        if (_dish == null)
            _dish = new Dish(this, Keys.DISH_INGREDIENTS__DISH_INGREDIENTS_DISH_ID_FKEY);

        return _dish;
    }

    /**
     * Get the implicit join path to the <code>public.food</code> table.
     */
    public Food food() {
        if (_food == null)
            _food = new Food(this, Keys.DISH_INGREDIENTS__DISH_INGREDIENTS_INGREDIENT_ID_FKEY);

        return _food;
    }

    @Override
    public DishIngredients as(String alias) {
        return new DishIngredients(DSL.name(alias), this);
    }

    @Override
    public DishIngredients as(Name alias) {
        return new DishIngredients(alias, this);
    }

    @Override
    public DishIngredients as(Table<?> alias) {
        return new DishIngredients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DishIngredients rename(String name) {
        return new DishIngredients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishIngredients rename(Name name) {
        return new DishIngredients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishIngredients rename(Table<?> name) {
        return new DishIngredients(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, BigDecimal, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super BigDecimal, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super BigDecimal, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
