/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Public;
import org.mvasylchuk.pfcc.jooq.tables.records.FoodIngredientsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FoodIngredients extends TableImpl<FoodIngredientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.food_ingredients</code>
     */
    public static final FoodIngredients FOOD_INGREDIENTS = new FoodIngredients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FoodIngredientsRecord> getRecordType() {
        return FoodIngredientsRecord.class;
    }

    /**
     * The column <code>public.food_ingredients.recipe_id</code>.
     */
    public final TableField<FoodIngredientsRecord, Long> RECIPE_ID = createField(DSL.name("recipe_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.food_ingredients.ingredient_id</code>.
     */
    public final TableField<FoodIngredientsRecord, Long> INGREDIENT_ID = createField(DSL.name("ingredient_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.food_ingredients.weight_in_gram</code>.
     */
    public final TableField<FoodIngredientsRecord, BigDecimal> WEIGHT_IN_GRAM = createField(DSL.name("weight_in_gram"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.food_ingredients.ingredient_index</code>.
     */
    public final TableField<FoodIngredientsRecord, Long> INGREDIENT_INDEX = createField(DSL.name("ingredient_index"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.food_ingredients.measurement_id</code>.
     */
    public final TableField<FoodIngredientsRecord, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.food_ingredients.measurement_name</code>.
     */
    public final TableField<FoodIngredientsRecord, String> MEASUREMENT_NAME = createField(DSL.name("measurement_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.food_ingredients.measurement_weight</code>.
     */
    public final TableField<FoodIngredientsRecord, BigDecimal> MEASUREMENT_WEIGHT = createField(DSL.name("measurement_weight"), SQLDataType.NUMERIC(9, 4), this, "");

    /**
     * The column <code>public.food_ingredients.is_default</code>.
     */
    public final TableField<FoodIngredientsRecord, Boolean> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private FoodIngredients(Name alias, Table<FoodIngredientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private FoodIngredients(Name alias, Table<FoodIngredientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.food_ingredients</code> table reference
     */
    public FoodIngredients(String alias) {
        this(DSL.name(alias), FOOD_INGREDIENTS);
    }

    /**
     * Create an aliased <code>public.food_ingredients</code> table reference
     */
    public FoodIngredients(Name alias) {
        this(alias, FOOD_INGREDIENTS);
    }

    /**
     * Create a <code>public.food_ingredients</code> table reference
     */
    public FoodIngredients() {
        this(DSL.name("food_ingredients"), null);
    }

    public <O extends Record> FoodIngredients(Table<O> child, ForeignKey<O, FoodIngredientsRecord> key) {
        super(child, key, FOOD_INGREDIENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FoodIngredientsRecord> getPrimaryKey() {
        return Keys.INGREDIENTS_PKEY;
    }

    @Override
    public List<ForeignKey<FoodIngredientsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FOOD_INGREDIENTS__INGREDIENTS_RECIPE_ID_FKEY, Keys.FOOD_INGREDIENTS__INGREDIENTS_INGREDIENT_ID_FKEY, Keys.FOOD_INGREDIENTS__FOOD_INGREDIENTS_MEASUREMENT_ID_FKEY);
    }

    private transient Food _ingredientsRecipeIdFkey;
    private transient Food _ingredientsIngredientIdFkey;
    private transient Measurement _measurement;

    /**
     * Get the implicit join path to the <code>public.food</code> table, via the
     * <code>ingredients_recipe_id_fkey</code> key.
     */
    public Food ingredientsRecipeIdFkey() {
        if (_ingredientsRecipeIdFkey == null)
            _ingredientsRecipeIdFkey = new Food(this, Keys.FOOD_INGREDIENTS__INGREDIENTS_RECIPE_ID_FKEY);

        return _ingredientsRecipeIdFkey;
    }

    /**
     * Get the implicit join path to the <code>public.food</code> table, via the
     * <code>ingredients_ingredient_id_fkey</code> key.
     */
    public Food ingredientsIngredientIdFkey() {
        if (_ingredientsIngredientIdFkey == null)
            _ingredientsIngredientIdFkey = new Food(this, Keys.FOOD_INGREDIENTS__INGREDIENTS_INGREDIENT_ID_FKEY);

        return _ingredientsIngredientIdFkey;
    }

    /**
     * Get the implicit join path to the <code>public.measurement</code> table.
     */
    public Measurement measurement() {
        if (_measurement == null)
            _measurement = new Measurement(this, Keys.FOOD_INGREDIENTS__FOOD_INGREDIENTS_MEASUREMENT_ID_FKEY);

        return _measurement;
    }

    @Override
    public FoodIngredients as(String alias) {
        return new FoodIngredients(DSL.name(alias), this);
    }

    @Override
    public FoodIngredients as(Name alias) {
        return new FoodIngredients(alias, this);
    }

    @Override
    public FoodIngredients as(Table<?> alias) {
        return new FoodIngredients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodIngredients rename(String name) {
        return new FoodIngredients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodIngredients rename(Name name) {
        return new FoodIngredients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodIngredients rename(Table<?> name) {
        return new FoodIngredients(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, BigDecimal, Long, Long, String, BigDecimal, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super Long, ? super BigDecimal, ? super Long, ? super Long, ? super String, ? super BigDecimal, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super Long, ? super BigDecimal, ? super Long, ? super Long, ? super String, ? super BigDecimal, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
