/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Indexes;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Pfcc;
import org.mvasylchuk.pfcc.jooq.tables.records.IngredientsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ingredients extends TableImpl<IngredientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pfcc.ingredients</code>
     */
    public static final Ingredients INGREDIENTS = new Ingredients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IngredientsRecord> getRecordType() {
        return IngredientsRecord.class;
    }

    /**
     * The column <code>pfcc.ingredients.recipe_id</code>.
     */
    public final TableField<IngredientsRecord, Long> RECIPE_ID = createField(DSL.name("recipe_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pfcc.ingredients.ingredient_id</code>.
     */
    public final TableField<IngredientsRecord, Long> INGREDIENT_ID = createField(DSL.name("ingredient_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pfcc.ingredients.ingredient_weight</code>.
     */
    public final TableField<IngredientsRecord, BigDecimal> INGREDIENT_WEIGHT = createField(DSL.name("ingredient_weight"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    private Ingredients(Name alias, Table<IngredientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ingredients(Name alias, Table<IngredientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pfcc.ingredients</code> table reference
     */
    public Ingredients(String alias) {
        this(DSL.name(alias), INGREDIENTS);
    }

    /**
     * Create an aliased <code>pfcc.ingredients</code> table reference
     */
    public Ingredients(Name alias) {
        this(alias, INGREDIENTS);
    }

    /**
     * Create a <code>pfcc.ingredients</code> table reference
     */
    public Ingredients() {
        this(DSL.name("ingredients"), null);
    }

    public <O extends Record> Ingredients(Table<O> child, ForeignKey<O, IngredientsRecord> key) {
        super(child, key, INGREDIENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pfcc.PFCC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INGREDIENTS_INGREDIENT_ID);
    }

    @Override
    public UniqueKey<IngredientsRecord> getPrimaryKey() {
        return Keys.KEY_INGREDIENTS_PRIMARY;
    }

    @Override
    public List<ForeignKey<IngredientsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INGREDIENTS_IBFK_1, Keys.INGREDIENTS_IBFK_2);
    }

    private transient Food _ingredientsIbfk_1;
    private transient Food _ingredientsIbfk_2;

    /**
     * Get the implicit join path to the <code>pfcc.food</code> table, via the
     * <code>ingredients_ibfk_1</code> key.
     */
    public Food ingredientsIbfk_1() {
        if (_ingredientsIbfk_1 == null)
            _ingredientsIbfk_1 = new Food(this, Keys.INGREDIENTS_IBFK_1);

        return _ingredientsIbfk_1;
    }

    /**
     * Get the implicit join path to the <code>pfcc.food</code> table, via the
     * <code>ingredients_ibfk_2</code> key.
     */
    public Food ingredientsIbfk_2() {
        if (_ingredientsIbfk_2 == null)
            _ingredientsIbfk_2 = new Food(this, Keys.INGREDIENTS_IBFK_2);

        return _ingredientsIbfk_2;
    }

    @Override
    public Ingredients as(String alias) {
        return new Ingredients(DSL.name(alias), this);
    }

    @Override
    public Ingredients as(Name alias) {
        return new Ingredients(alias, this);
    }

    @Override
    public Ingredients as(Table<?> alias) {
        return new Ingredients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredients rename(String name) {
        return new Ingredients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredients rename(Name name) {
        return new Ingredients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredients rename(Table<?> name) {
        return new Ingredients(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super BigDecimal, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super BigDecimal, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
