/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Public;
import org.mvasylchuk.pfcc.jooq.tables.records.MealRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Meal extends TableImpl<MealRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.meal</code>
     */
    public static final Meal MEAL = new Meal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MealRecord> getRecordType() {
        return MealRecord.class;
    }

    /**
     * The column <code>public.meal.id</code>.
     */
    public final TableField<MealRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.meal.weight_in_gram</code>.
     */
    public final TableField<MealRecord, BigDecimal> WEIGHT_IN_GRAM = createField(DSL.name("weight_in_gram"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal.protein</code>.
     */
    public final TableField<MealRecord, BigDecimal> PROTEIN = createField(DSL.name("protein"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal.fat</code>.
     */
    public final TableField<MealRecord, BigDecimal> FAT = createField(DSL.name("fat"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal.carbohydrates</code>.
     */
    public final TableField<MealRecord, BigDecimal> CARBOHYDRATES = createField(DSL.name("carbohydrates"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal.calories</code>.
     */
    public final TableField<MealRecord, BigDecimal> CALORIES = createField(DSL.name("calories"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal.food_id</code>.
     */
    public final TableField<MealRecord, Long> FOOD_ID = createField(DSL.name("food_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.meal.eaten_on</code>.
     */
    public final TableField<MealRecord, LocalDateTime> EATEN_ON = createField(DSL.name("eaten_on"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.meal.owner_id</code>.
     */
    public final TableField<MealRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.meal.measurement_id</code>.
     */
    public final TableField<MealRecord, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.meal.measurement_name</code>.
     */
    public final TableField<MealRecord, String> MEASUREMENT_NAME = createField(DSL.name("measurement_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.meal.measurement_weight</code>.
     */
    public final TableField<MealRecord, BigDecimal> MEASUREMENT_WEIGHT = createField(DSL.name("measurement_weight"), SQLDataType.NUMERIC(9, 4), this, "");

    private Meal(Name alias, Table<MealRecord> aliased) {
        this(alias, aliased, null);
    }

    private Meal(Name alias, Table<MealRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.meal</code> table reference
     */
    public Meal(String alias) {
        this(DSL.name(alias), MEAL);
    }

    /**
     * Create an aliased <code>public.meal</code> table reference
     */
    public Meal(Name alias) {
        this(alias, MEAL);
    }

    /**
     * Create a <code>public.meal</code> table reference
     */
    public Meal() {
        this(DSL.name("meal"), null);
    }

    public <O extends Record> Meal(Table<O> child, ForeignKey<O, MealRecord> key) {
        super(child, key, MEAL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MealRecord, Long> getIdentity() {
        return (Identity<MealRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MealRecord> getPrimaryKey() {
        return Keys.MEAL_PKEY;
    }

    @Override
    public List<ForeignKey<MealRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEAL__MEAL_FOOD_ID_FKEY, Keys.MEAL__MEAL_OWNER_ID_FKEY, Keys.MEAL__MEAL_MEASUREMENT_ID_FKEY);
    }

    private transient Food _food;
    private transient Users _users;
    private transient Measurement _measurement;

    /**
     * Get the implicit join path to the <code>public.food</code> table.
     */
    public Food food() {
        if (_food == null)
            _food = new Food(this, Keys.MEAL__MEAL_FOOD_ID_FKEY);

        return _food;
    }

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.MEAL__MEAL_OWNER_ID_FKEY);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.measurement</code> table.
     */
    public Measurement measurement() {
        if (_measurement == null)
            _measurement = new Measurement(this, Keys.MEAL__MEAL_MEASUREMENT_ID_FKEY);

        return _measurement;
    }

    @Override
    public Meal as(String alias) {
        return new Meal(DSL.name(alias), this);
    }

    @Override
    public Meal as(Name alias) {
        return new Meal(alias, this);
    }

    @Override
    public Meal as(Table<?> alias) {
        return new Meal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(String name) {
        return new Meal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(Name name) {
        return new Meal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(Table<?> name) {
        return new Meal(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long, LocalDateTime, Long, Long, String, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super Long, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super LocalDateTime, ? super Long, ? super Long, ? super String, ? super BigDecimal, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super Long, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super LocalDateTime, ? super Long, ? super Long, ? super String, ? super BigDecimal, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
