/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Indexes;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Pfcc;
import org.mvasylchuk.pfcc.jooq.tables.records.MealRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meal extends TableImpl<MealRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pfcc.meal</code>
     */
    public static final Meal MEAL = new Meal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MealRecord> getRecordType() {
        return MealRecord.class;
    }

    /**
     * The column <code>pfcc.meal.id</code>.
     */
    public final TableField<MealRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval(`pfcc`.`meal_id_seq`)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pfcc.meal.weight</code>.
     */
    public final TableField<MealRecord, BigDecimal> WEIGHT = createField(DSL.name("weight"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.protein</code>.
     */
    public final TableField<MealRecord, BigDecimal> PROTEIN = createField(DSL.name("protein"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.fat</code>.
     */
    public final TableField<MealRecord, BigDecimal> FAT = createField(DSL.name("fat"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.carbohydrates</code>.
     */
    public final TableField<MealRecord, BigDecimal> CARBOHYDRATES = createField(DSL.name("carbohydrates"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.calories</code>.
     */
    public final TableField<MealRecord, BigDecimal> CALORIES = createField(DSL.name("calories"), SQLDataType.DECIMAL(9, 4).nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.food_id</code>.
     */
    public final TableField<MealRecord, Long> FOOD_ID = createField(DSL.name("food_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pfcc.meal.dish_id</code>.
     */
    public final TableField<MealRecord, Long> DISH_ID = createField(DSL.name("dish_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>pfcc.meal.eaten_on</code>.
     */
    public final TableField<MealRecord, LocalDateTime> EATEN_ON = createField(DSL.name("eaten_on"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>pfcc.meal.owner_id</code>.
     */
    public final TableField<MealRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Meal(Name alias, Table<MealRecord> aliased) {
        this(alias, aliased, null);
    }

    private Meal(Name alias, Table<MealRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pfcc.meal</code> table reference
     */
    public Meal(String alias) {
        this(DSL.name(alias), MEAL);
    }

    /**
     * Create an aliased <code>pfcc.meal</code> table reference
     */
    public Meal(Name alias) {
        this(alias, MEAL);
    }

    /**
     * Create a <code>pfcc.meal</code> table reference
     */
    public Meal() {
        this(DSL.name("meal"), null);
    }

    public <O extends Record> Meal(Table<O> child, ForeignKey<O, MealRecord> key) {
        super(child, key, MEAL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pfcc.PFCC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEAL_DISH_ID, Indexes.MEAL_FOOD_ID, Indexes.MEAL_OWNER_ID);
    }

    @Override
    public UniqueKey<MealRecord> getPrimaryKey() {
        return Keys.KEY_MEAL_PRIMARY;
    }

    @Override
    public List<ForeignKey<MealRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEAL_IBFK_1, Keys.MEAL_IBFK_2, Keys.MEAL_IBFK_3);
    }

    private transient Food _food;
    private transient Dish _dish;
    private transient Users _users;

    /**
     * Get the implicit join path to the <code>pfcc.food</code> table.
     */
    public Food food() {
        if (_food == null)
            _food = new Food(this, Keys.MEAL_IBFK_1);

        return _food;
    }

    /**
     * Get the implicit join path to the <code>pfcc.dish</code> table.
     */
    public Dish dish() {
        if (_dish == null)
            _dish = new Dish(this, Keys.MEAL_IBFK_2);

        return _dish;
    }

    /**
     * Get the implicit join path to the <code>pfcc.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.MEAL_IBFK_3);

        return _users;
    }

    @Override
    public Meal as(String alias) {
        return new Meal(DSL.name(alias), this);
    }

    @Override
    public Meal as(Name alias) {
        return new Meal(alias, this);
    }

    @Override
    public Meal as(Table<?> alias) {
        return new Meal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(String name) {
        return new Meal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(Name name) {
        return new Meal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meal rename(Table<?> name) {
        return new Meal(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long, Long, LocalDateTime, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Long, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super Long, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Long, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super Long, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
