/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Public;
import org.mvasylchuk.pfcc.jooq.tables.records.MealIngredientsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MealIngredients extends TableImpl<MealIngredientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.meal_ingredients</code>
     */
    public static final MealIngredients MEAL_INGREDIENTS = new MealIngredients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MealIngredientsRecord> getRecordType() {
        return MealIngredientsRecord.class;
    }

    /**
     * The column <code>public.meal_ingredients.meal_id</code>.
     */
    public final TableField<MealIngredientsRecord, Long> MEAL_ID = createField(DSL.name("meal_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.meal_ingredients.ingredient_id</code>.
     */
    public final TableField<MealIngredientsRecord, Long> INGREDIENT_ID = createField(DSL.name("ingredient_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.meal_ingredients.measurement_id</code>.
     */
    public final TableField<MealIngredientsRecord, Long> MEASUREMENT_ID = createField(DSL.name("measurement_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.meal_ingredients.measurement_weight</code>.
     */
    public final TableField<MealIngredientsRecord, BigDecimal> MEASUREMENT_WEIGHT = createField(DSL.name("measurement_weight"), SQLDataType.NUMERIC(9, 4), this, "");

    /**
     * The column <code>public.meal_ingredients.measurement_name</code>.
     */
    public final TableField<MealIngredientsRecord, String> MEASUREMENT_NAME = createField(DSL.name("measurement_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.meal_ingredients.weight_in_gram</code>.
     */
    public final TableField<MealIngredientsRecord, BigDecimal> WEIGHT_IN_GRAM = createField(DSL.name("weight_in_gram"), SQLDataType.NUMERIC(9, 4).nullable(false), this, "");

    /**
     * The column <code>public.meal_ingredients.ingredient_index</code>.
     */
    public final TableField<MealIngredientsRecord, Long> INGREDIENT_INDEX = createField(DSL.name("ingredient_index"), SQLDataType.BIGINT.nullable(false), this, "");

    private MealIngredients(Name alias, Table<MealIngredientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MealIngredients(Name alias, Table<MealIngredientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.meal_ingredients</code> table reference
     */
    public MealIngredients(String alias) {
        this(DSL.name(alias), MEAL_INGREDIENTS);
    }

    /**
     * Create an aliased <code>public.meal_ingredients</code> table reference
     */
    public MealIngredients(Name alias) {
        this(alias, MEAL_INGREDIENTS);
    }

    /**
     * Create a <code>public.meal_ingredients</code> table reference
     */
    public MealIngredients() {
        this(DSL.name("meal_ingredients"), null);
    }

    public <O extends Record> MealIngredients(Table<O> child, ForeignKey<O, MealIngredientsRecord> key) {
        super(child, key, MEAL_INGREDIENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MealIngredientsRecord> getPrimaryKey() {
        return Keys.MEAL_INGREDIENTS_PKEY;
    }

    @Override
    public List<ForeignKey<MealIngredientsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_MEAL_ID_FKEY, Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_INGREDIENT_ID_FKEY, Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_MEASUREMENT_ID_FKEY);
    }

    private transient Meal _meal;
    private transient Food _food;
    private transient Measurement _measurement;

    /**
     * Get the implicit join path to the <code>public.meal</code> table.
     */
    public Meal meal() {
        if (_meal == null)
            _meal = new Meal(this, Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_MEAL_ID_FKEY);

        return _meal;
    }

    /**
     * Get the implicit join path to the <code>public.food</code> table.
     */
    public Food food() {
        if (_food == null)
            _food = new Food(this, Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_INGREDIENT_ID_FKEY);

        return _food;
    }

    /**
     * Get the implicit join path to the <code>public.measurement</code> table.
     */
    public Measurement measurement() {
        if (_measurement == null)
            _measurement = new Measurement(this, Keys.MEAL_INGREDIENTS__MEAL_INGREDIENTS_MEASUREMENT_ID_FKEY);

        return _measurement;
    }

    @Override
    public MealIngredients as(String alias) {
        return new MealIngredients(DSL.name(alias), this);
    }

    @Override
    public MealIngredients as(Name alias) {
        return new MealIngredients(alias, this);
    }

    @Override
    public MealIngredients as(Table<?> alias) {
        return new MealIngredients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MealIngredients rename(String name) {
        return new MealIngredients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MealIngredients rename(Name name) {
        return new MealIngredients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MealIngredients rename(Table<?> name) {
        return new MealIngredients(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, BigDecimal, String, BigDecimal, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super Long, ? super Long, ? super BigDecimal, ? super String, ? super BigDecimal, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super Long, ? super Long, ? super BigDecimal, ? super String, ? super BigDecimal, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
