/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.mvasylchuk.pfcc.jooq.Keys;
import org.mvasylchuk.pfcc.jooq.Public;
import org.mvasylchuk.pfcc.jooq.tables.records.ReportsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reports extends TableImpl<ReportsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.reports</code>
     */
    public static final Reports REPORTS = new Reports();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportsRecord> getRecordType() {
        return ReportsRecord.class;
    }

    /**
     * The column <code>public.reports.id</code>.
     */
    public final TableField<ReportsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.reports.user_id</code>.
     */
    public final TableField<ReportsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.reports.name</code>.
     */
    public final TableField<ReportsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.reports.file_path</code>.
     */
    public final TableField<ReportsRecord, String> FILE_PATH = createField(DSL.name("file_path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.reports.status</code>.
     */
    public final TableField<ReportsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.reports.type</code>.
     */
    public final TableField<ReportsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.reports.created_at</code>.
     */
    public final TableField<ReportsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Reports(Name alias, Table<ReportsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Reports(Name alias, Table<ReportsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.reports</code> table reference
     */
    public Reports(String alias) {
        this(DSL.name(alias), REPORTS);
    }

    /**
     * Create an aliased <code>public.reports</code> table reference
     */
    public Reports(Name alias) {
        this(alias, REPORTS);
    }

    /**
     * Create a <code>public.reports</code> table reference
     */
    public Reports() {
        this(DSL.name("reports"), null);
    }

    public <O extends Record> Reports(Table<O> child, ForeignKey<O, ReportsRecord> key) {
        super(child, key, REPORTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ReportsRecord, Long> getIdentity() {
        return (Identity<ReportsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReportsRecord> getPrimaryKey() {
        return Keys.REPORTS_PKEY;
    }

    @Override
    public List<UniqueKey<ReportsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REPORTS_NAME_KEY, Keys.REPORTS_FILE_PATH_KEY);
    }

    @Override
    public List<ForeignKey<ReportsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORTS__REPORTS_USER_ID_FKEY);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.REPORTS__REPORTS_USER_ID_FKEY);

        return _users;
    }

    @Override
    public Reports as(String alias) {
        return new Reports(DSL.name(alias), this);
    }

    @Override
    public Reports as(Name alias) {
        return new Reports(alias, this);
    }

    @Override
    public Reports as(Table<?> alias) {
        return new Reports(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reports rename(String name) {
        return new Reports(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reports rename(Name name) {
        return new Reports(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reports rename(Table<?> name) {
        return new Reports(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
