INSERT INTO users (id, email, name, preferred_language, protein_aim,
                   fat_aim, carbohydrates_aim, calories_aim,
                   profile_configured, email_confirmed, password, roles)
VALUES (1,
        'email',
        'name',
        'UA',
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        TRUE,
        'pass',
        'USER')
