/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.mvasylchuk.pfcc.jooq.tables.FoodIngredients;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FoodIngredientsRecord extends UpdatableRecordImpl<FoodIngredientsRecord> implements Record8<Long, Long, BigDecimal, Long, Long, String, BigDecimal, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.food_ingredients.recipe_id</code>.
     */
    public void setRecipeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.food_ingredients.recipe_id</code>.
     */
    public Long getRecipeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.food_ingredients.ingredient_id</code>.
     */
    public void setIngredientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.food_ingredients.ingredient_id</code>.
     */
    public Long getIngredientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.food_ingredients.weight_in_gram</code>.
     */
    public void setWeightInGram(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.food_ingredients.weight_in_gram</code>.
     */
    public BigDecimal getWeightInGram() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.food_ingredients.ingredient_index</code>.
     */
    public void setIngredientIndex(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.food_ingredients.ingredient_index</code>.
     */
    public Long getIngredientIndex() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.food_ingredients.measurement_id</code>.
     */
    public void setMeasurementId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.food_ingredients.measurement_id</code>.
     */
    public Long getMeasurementId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.food_ingredients.measurement_name</code>.
     */
    public void setMeasurementName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.food_ingredients.measurement_name</code>.
     */
    public String getMeasurementName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.food_ingredients.measurement_weight</code>.
     */
    public void setMeasurementWeight(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.food_ingredients.measurement_weight</code>.
     */
    public BigDecimal getMeasurementWeight() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.food_ingredients.is_default</code>.
     */
    public void setIsDefault(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.food_ingredients.is_default</code>.
     */
    public Boolean getIsDefault() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, BigDecimal, Long, Long, String, BigDecimal, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, BigDecimal, Long, Long, String, BigDecimal, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FoodIngredients.FOOD_INGREDIENTS.RECIPE_ID;
    }

    @Override
    public Field<Long> field2() {
        return FoodIngredients.FOOD_INGREDIENTS.INGREDIENT_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return FoodIngredients.FOOD_INGREDIENTS.WEIGHT_IN_GRAM;
    }

    @Override
    public Field<Long> field4() {
        return FoodIngredients.FOOD_INGREDIENTS.INGREDIENT_INDEX;
    }

    @Override
    public Field<Long> field5() {
        return FoodIngredients.FOOD_INGREDIENTS.MEASUREMENT_ID;
    }

    @Override
    public Field<String> field6() {
        return FoodIngredients.FOOD_INGREDIENTS.MEASUREMENT_NAME;
    }

    @Override
    public Field<BigDecimal> field7() {
        return FoodIngredients.FOOD_INGREDIENTS.MEASUREMENT_WEIGHT;
    }

    @Override
    public Field<Boolean> field8() {
        return FoodIngredients.FOOD_INGREDIENTS.IS_DEFAULT;
    }

    @Override
    public Long component1() {
        return getRecipeId();
    }

    @Override
    public Long component2() {
        return getIngredientId();
    }

    @Override
    public BigDecimal component3() {
        return getWeightInGram();
    }

    @Override
    public Long component4() {
        return getIngredientIndex();
    }

    @Override
    public Long component5() {
        return getMeasurementId();
    }

    @Override
    public String component6() {
        return getMeasurementName();
    }

    @Override
    public BigDecimal component7() {
        return getMeasurementWeight();
    }

    @Override
    public Boolean component8() {
        return getIsDefault();
    }

    @Override
    public Long value1() {
        return getRecipeId();
    }

    @Override
    public Long value2() {
        return getIngredientId();
    }

    @Override
    public BigDecimal value3() {
        return getWeightInGram();
    }

    @Override
    public Long value4() {
        return getIngredientIndex();
    }

    @Override
    public Long value5() {
        return getMeasurementId();
    }

    @Override
    public String value6() {
        return getMeasurementName();
    }

    @Override
    public BigDecimal value7() {
        return getMeasurementWeight();
    }

    @Override
    public Boolean value8() {
        return getIsDefault();
    }

    @Override
    public FoodIngredientsRecord value1(Long value) {
        setRecipeId(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value2(Long value) {
        setIngredientId(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value3(BigDecimal value) {
        setWeightInGram(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value4(Long value) {
        setIngredientIndex(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value5(Long value) {
        setMeasurementId(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value6(String value) {
        setMeasurementName(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value7(BigDecimal value) {
        setMeasurementWeight(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord value8(Boolean value) {
        setIsDefault(value);
        return this;
    }

    @Override
    public FoodIngredientsRecord values(Long value1, Long value2, BigDecimal value3, Long value4, Long value5, String value6, BigDecimal value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FoodIngredientsRecord
     */
    public FoodIngredientsRecord() {
        super(FoodIngredients.FOOD_INGREDIENTS);
    }

    /**
     * Create a detached, initialised FoodIngredientsRecord
     */
    public FoodIngredientsRecord(Long recipeId, Long ingredientId, BigDecimal weightInGram, Long ingredientIndex, Long measurementId, String measurementName, BigDecimal measurementWeight, Boolean isDefault) {
        super(FoodIngredients.FOOD_INGREDIENTS);

        setRecipeId(recipeId);
        setIngredientId(ingredientId);
        setWeightInGram(weightInGram);
        setIngredientIndex(ingredientIndex);
        setMeasurementId(measurementId);
        setMeasurementName(measurementName);
        setMeasurementWeight(measurementWeight);
        setIsDefault(isDefault);
        resetChangedOnNotNull();
    }
}
