/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.mvasylchuk.pfcc.jooq.tables.MealIngredients;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MealIngredientsRecord extends UpdatableRecordImpl<MealIngredientsRecord> implements Record7<Long, Long, Long, BigDecimal, String, BigDecimal, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.meal_ingredients.meal_id</code>.
     */
    public void setMealId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.meal_id</code>.
     */
    public Long getMealId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.meal_ingredients.ingredient_id</code>.
     */
    public void setIngredientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.ingredient_id</code>.
     */
    public Long getIngredientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.meal_ingredients.measurement_id</code>.
     */
    public void setMeasurementId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.measurement_id</code>.
     */
    public Long getMeasurementId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.meal_ingredients.measurement_weight</code>.
     */
    public void setMeasurementWeight(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.measurement_weight</code>.
     */
    public BigDecimal getMeasurementWeight() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.meal_ingredients.measurement_name</code>.
     */
    public void setMeasurementName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.measurement_name</code>.
     */
    public String getMeasurementName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.meal_ingredients.weight_in_gram</code>.
     */
    public void setWeightInGram(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.weight_in_gram</code>.
     */
    public BigDecimal getWeightInGram() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.meal_ingredients.ingredient_index</code>.
     */
    public void setIngredientIndex(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.meal_ingredients.ingredient_index</code>.
     */
    public Long getIngredientIndex() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, BigDecimal, String, BigDecimal, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, BigDecimal, String, BigDecimal, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MealIngredients.MEAL_INGREDIENTS.MEAL_ID;
    }

    @Override
    public Field<Long> field2() {
        return MealIngredients.MEAL_INGREDIENTS.INGREDIENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return MealIngredients.MEAL_INGREDIENTS.MEASUREMENT_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return MealIngredients.MEAL_INGREDIENTS.MEASUREMENT_WEIGHT;
    }

    @Override
    public Field<String> field5() {
        return MealIngredients.MEAL_INGREDIENTS.MEASUREMENT_NAME;
    }

    @Override
    public Field<BigDecimal> field6() {
        return MealIngredients.MEAL_INGREDIENTS.WEIGHT_IN_GRAM;
    }

    @Override
    public Field<Long> field7() {
        return MealIngredients.MEAL_INGREDIENTS.INGREDIENT_INDEX;
    }

    @Override
    public Long component1() {
        return getMealId();
    }

    @Override
    public Long component2() {
        return getIngredientId();
    }

    @Override
    public Long component3() {
        return getMeasurementId();
    }

    @Override
    public BigDecimal component4() {
        return getMeasurementWeight();
    }

    @Override
    public String component5() {
        return getMeasurementName();
    }

    @Override
    public BigDecimal component6() {
        return getWeightInGram();
    }

    @Override
    public Long component7() {
        return getIngredientIndex();
    }

    @Override
    public Long value1() {
        return getMealId();
    }

    @Override
    public Long value2() {
        return getIngredientId();
    }

    @Override
    public Long value3() {
        return getMeasurementId();
    }

    @Override
    public BigDecimal value4() {
        return getMeasurementWeight();
    }

    @Override
    public String value5() {
        return getMeasurementName();
    }

    @Override
    public BigDecimal value6() {
        return getWeightInGram();
    }

    @Override
    public Long value7() {
        return getIngredientIndex();
    }

    @Override
    public MealIngredientsRecord value1(Long value) {
        setMealId(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value2(Long value) {
        setIngredientId(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value3(Long value) {
        setMeasurementId(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value4(BigDecimal value) {
        setMeasurementWeight(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value5(String value) {
        setMeasurementName(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value6(BigDecimal value) {
        setWeightInGram(value);
        return this;
    }

    @Override
    public MealIngredientsRecord value7(Long value) {
        setIngredientIndex(value);
        return this;
    }

    @Override
    public MealIngredientsRecord values(Long value1, Long value2, Long value3, BigDecimal value4, String value5, BigDecimal value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MealIngredientsRecord
     */
    public MealIngredientsRecord() {
        super(MealIngredients.MEAL_INGREDIENTS);
    }

    /**
     * Create a detached, initialised MealIngredientsRecord
     */
    public MealIngredientsRecord(Long mealId, Long ingredientId, Long measurementId, BigDecimal measurementWeight, String measurementName, BigDecimal weightInGram, Long ingredientIndex) {
        super(MealIngredients.MEAL_INGREDIENTS);

        setMealId(mealId);
        setIngredientId(ingredientId);
        setMeasurementId(measurementId);
        setMeasurementWeight(measurementWeight);
        setMeasurementName(measurementName);
        setWeightInGram(weightInGram);
        setIngredientIndex(ingredientIndex);
        resetChangedOnNotNull();
    }
}
