/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.mvasylchuk.pfcc.jooq.tables.SecurityTokens;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityTokensRecord extends UpdatableRecordImpl<SecurityTokensRecord> implements Record8<Long, String, Long, String, Boolean, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.security_tokens.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.security_tokens.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.security_tokens.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.security_tokens.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.security_tokens.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.security_tokens.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.security_tokens.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.security_tokens.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.security_tokens.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.security_tokens.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.security_tokens.valid_until</code>.
     */
    public void setValidUntil(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.security_tokens.valid_until</code>.
     */
    public LocalDateTime getValidUntil() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.security_tokens.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.security_tokens.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.security_tokens.modified_at</code>.
     */
    public void setModifiedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.security_tokens.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, Long, String, Boolean, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, Long, String, Boolean, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SecurityTokens.SECURITY_TOKENS.ID;
    }

    @Override
    public Field<String> field2() {
        return SecurityTokens.SECURITY_TOKENS.CODE;
    }

    @Override
    public Field<Long> field3() {
        return SecurityTokens.SECURITY_TOKENS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return SecurityTokens.SECURITY_TOKENS.TYPE;
    }

    @Override
    public Field<Boolean> field5() {
        return SecurityTokens.SECURITY_TOKENS.IS_ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SecurityTokens.SECURITY_TOKENS.VALID_UNTIL;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SecurityTokens.SECURITY_TOKENS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return SecurityTokens.SECURITY_TOKENS.MODIFIED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public Boolean component5() {
        return getIsActive();
    }

    @Override
    public LocalDateTime component6() {
        return getValidUntil();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public Boolean value5() {
        return getIsActive();
    }

    @Override
    public LocalDateTime value6() {
        return getValidUntil();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedAt();
    }

    @Override
    public SecurityTokensRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value5(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value6(LocalDateTime value) {
        setValidUntil(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SecurityTokensRecord value8(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public SecurityTokensRecord values(Long value1, String value2, Long value3, String value4, Boolean value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityTokensRecord
     */
    public SecurityTokensRecord() {
        super(SecurityTokens.SECURITY_TOKENS);
    }

    /**
     * Create a detached, initialised SecurityTokensRecord
     */
    public SecurityTokensRecord(Long id, String code, Long userId, String type, Boolean isActive, LocalDateTime validUntil, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(SecurityTokens.SECURITY_TOKENS);

        setId(id);
        setCode(code);
        setUserId(userId);
        setType(type);
        setIsActive(isActive);
        setValidUntil(validUntil);
        setCreatedAt(createdAt);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
