/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.mvasylchuk.pfcc.jooq.tables.Food;
import org.mvasylchuk.pfcc.jooq.tables.FoodIngredients;
import org.mvasylchuk.pfcc.jooq.tables.Meal;
import org.mvasylchuk.pfcc.jooq.tables.MealIngredients;
import org.mvasylchuk.pfcc.jooq.tables.Measurement;
import org.mvasylchuk.pfcc.jooq.tables.Reports;
import org.mvasylchuk.pfcc.jooq.tables.SecurityTokens;
import org.mvasylchuk.pfcc.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.food</code>.
     */
    public final Food FOOD = Food.FOOD;

    /**
     * The table <code>public.food_ingredients</code>.
     */
    public final FoodIngredients FOOD_INGREDIENTS = FoodIngredients.FOOD_INGREDIENTS;

    /**
     * The table <code>public.meal</code>.
     */
    public final Meal MEAL = Meal.MEAL;

    /**
     * The table <code>public.meal_ingredients</code>.
     */
    public final MealIngredients MEAL_INGREDIENTS = MealIngredients.MEAL_INGREDIENTS;

    /**
     * The table <code>public.measurement</code>.
     */
    public final Measurement MEASUREMENT = Measurement.MEASUREMENT;

    /**
     * The table <code>public.reports</code>.
     */
    public final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>public.security_tokens</code>.
     */
    public final SecurityTokens SECURITY_TOKENS = SecurityTokens.SECURITY_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Food.FOOD,
            FoodIngredients.FOOD_INGREDIENTS,
            Meal.MEAL,
            MealIngredients.MEAL_INGREDIENTS,
            Measurement.MEASUREMENT,
            Reports.REPORTS,
            SecurityTokens.SECURITY_TOKENS,
            Users.USERS
        );
    }
}
