/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq;


import org.mvasylchuk.pfcc.jooq.tables.Food;
import org.mvasylchuk.pfcc.jooq.tables.FoodIngredients;
import org.mvasylchuk.pfcc.jooq.tables.Meal;
import org.mvasylchuk.pfcc.jooq.tables.MealIngredients;
import org.mvasylchuk.pfcc.jooq.tables.Measurement;
import org.mvasylchuk.pfcc.jooq.tables.Reports;
import org.mvasylchuk.pfcc.jooq.tables.SecurityTokens;
import org.mvasylchuk.pfcc.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.food</code>.
     */
    public static final Food FOOD = Food.FOOD;

    /**
     * The table <code>public.food_ingredients</code>.
     */
    public static final FoodIngredients FOOD_INGREDIENTS = FoodIngredients.FOOD_INGREDIENTS;

    /**
     * The table <code>public.meal</code>.
     */
    public static final Meal MEAL = Meal.MEAL;

    /**
     * The table <code>public.meal_ingredients</code>.
     */
    public static final MealIngredients MEAL_INGREDIENTS = MealIngredients.MEAL_INGREDIENTS;

    /**
     * The table <code>public.measurement</code>.
     */
    public static final Measurement MEASUREMENT = Measurement.MEASUREMENT;

    /**
     * The table <code>public.reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>public.security_tokens</code>.
     */
    public static final SecurityTokens SECURITY_TOKENS = SecurityTokens.SECURITY_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
