/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq;


import org.mvasylchuk.pfcc.jooq.tables.Users;


/**
 * Convenience access to all tables in pfcc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pfcc.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
