/*
 * This file is generated by jOOQ.
 */
package org.mvasylchuk.pfcc.jooq;


import org.mvasylchuk.pfcc.jooq.tables.Dish;
import org.mvasylchuk.pfcc.jooq.tables.Food;
import org.mvasylchuk.pfcc.jooq.tables.Ingredients;
import org.mvasylchuk.pfcc.jooq.tables.Meal;
import org.mvasylchuk.pfcc.jooq.tables.Users;


/**
 * Convenience access to all tables in pfcc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pfcc.dish</code>.
     */
    public static final Dish DISH = Dish.DISH;

    /**
     * The table <code>pfcc.food</code>.
     */
    public static final Food FOOD = Food.FOOD;

    /**
     * The table <code>pfcc.ingredients</code>.
     */
    public static final Ingredients INGREDIENTS = Ingredients.INGREDIENTS;

    /**
     * The table <code>pfcc.meal</code>.
     */
    public static final Meal MEAL = Meal.MEAL;

    /**
     * The table <code>pfcc.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
