package org.mvasylchuk.pfcc.platform.error;

public enum ApiErrorCode {
    USER_IS_NOT_OWNER, VALIDATION, FOOD_IS_DELETED, DISH_IS_NOT_FOUND, SECURITY, INVALID_CSV_FILE, MEASUREMENT_IS_NOT_FOUND, MEASUREMENTS_ARE_NOT_FOUND_WITH_THIS_FOOD_ID, FOOD_IS_NOT_FOUND
}
