ALTER SEQUENCE dish_id_seq
    INCREMENT BY 1;

ALTER SEQUENCE food_id_seq
    INCREMENT BY 1;

ALTER SEQUENCE meal_id_seq
    INCREMENT BY 1;

ALTER SEQUENCE security_token_id_seq
    INCREMENT BY 1;

ALTER SEQUENCE user_id_seq
    INCREMENT BY 1;