CREATE TABLE users
(
    id                 BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255)  NOT NULL UNIQUE,
    preferred_language VARCHAR(3)    NOT NULL,
    protein_aim        DECIMAL(9, 4) NULL,
    fat_aim            DECIMAL(9, 4) NULL,
    carbohydrates_aim  DECIMAL(9, 4) NULL,
    calories_aim       DECIMAL(9, 4) NULL,
    email_confirmed    BOOLEAN       NULL,
    password           VARCHAR(255)  NOT NULL,
    roles              VARCHAR(255)  NOT NULL,
    name               VARCHAR(255)  NOT NULL
);

CREATE TABLE food
(
    id            BIGINT                NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)          NOT NULL,
    type          VARCHAR(10)           NOT NULL,
    protein       DECIMAL(9, 4)         NOT NULL,
    fat           DECIMAL(9, 4)         NOT NULL,
    carbohydrates DECIMAL(9, 4)         NOT NULL,
    calories      DECIMAL(9, 4)         NOT NULL,
    is_hidden     BOOLEAN DEFAULT FALSE NOT NULL,
    owner_id      BIGINT                NULL REFERENCES users (id),
    description   TEXT                  NULL,
    deleted       BOOLEAN DEFAULT FALSE NOT NULL
);


CREATE TABLE dish
(
    id            BIGINT                  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)            NOT NULL,
    food_id       BIGINT                  NOT NULL REFERENCES food (id),
    recipe_weight DECIMAL(9, 4)           NOT NULL,
    cooked_weight DECIMAL(9, 4)           NOT NULL,
    protein       DECIMAL(9, 4)           NOT NULL,
    fat           DECIMAL(9, 4)           NOT NULL,
    carbohydrates DECIMAL(9, 4)           NOT NULL,
    calories      DECIMAL(9, 4)           NOT NULL,
    cooked_on     TIMESTAMP DEFAULT NOW() NULL,
    deleted       BOOLEAN   DEFAULT FALSE NOT NULL,
    owner_id      BIGINT                  NULL REFERENCES users (id)
);

CREATE TABLE dish_ingredients
(
    dish_id           BIGINT        NOT NULL REFERENCES dish (id),
    ingredient_id     BIGINT        NOT NULL REFERENCES food (id),
    ingredient_weight DECIMAL(9, 4) NOT NULL,
    ingredient_index  BIGINT        NOT NULL,
    PRIMARY KEY (dish_id, ingredient_id)
);

CREATE TABLE ingredients
(
    recipe_id         BIGINT        NOT NULL REFERENCES food (id),
    ingredient_id     BIGINT        NOT NULL REFERENCES food (id),
    ingredient_weight DECIMAL(9, 4) NOT NULL,
    ingredient_index  BIGINT        NOT NULL,
    PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE meal
(
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight        DECIMAL(9, 4) NOT NULL,
    protein       DECIMAL(9, 4) NOT NULL,
    fat           DECIMAL(9, 4) NOT NULL,
    carbohydrates DECIMAL(9, 4) NOT NULL,
    calories      DECIMAL(9, 4) NOT NULL,
    food_id       BIGINT        NOT NULL REFERENCES food (id),
    dish_id       BIGINT        NULL REFERENCES dish (id),
    eaten_on      TIMESTAMP DEFAULT NOW() NULL,
    owner_id      BIGINT        NOT NULL REFERENCES users (id)
);

CREATE TABLE measurement
(
    id                 BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id            BIGINT        NULL REFERENCES food (id),
    to_gram_multiplier DECIMAL(9, 4) NOT NULL,
    name               VARCHAR(255)  NOT NULL,
    default_value      DECIMAL(9, 4) NOT NULL
);

CREATE TABLE reports
(
    id         BIGINT                  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                  NOT NULL REFERENCES users (id),
    name       VARCHAR(255)            NOT NULL UNIQUE,
    file_path  VARCHAR(255)            NULL UNIQUE,
    status     VARCHAR(30)             NOT NULL,
    type       VARCHAR(30)             NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE security_tokens
(
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL UNIQUE,
    user_id     BIGINT       NULL REFERENCES users (id),
    type        VARCHAR(30)  NOT NULL,
    is_active   BOOLEAN      NULL,
    valid_until TIMESTAMP    NULL,
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL
);
